### ISSUE TITLE
cannot import name INA219

### ISSUE THREAD

**Issue by syjsxxjy** [chrisb2/pi_ina219#17]
```
pi@raspberrypi:~/shabi/python$ python ina219.py
Traceback (most recent call last):
  File "ina219.py", line 4, in <module>
    from ina219 import INA219
  File "/home/pi/shabi/python/ina219.py", line 4, in <module>
    from ina219 import INA219
ImportError: cannot import name INA219
```
and I tried to pip3 install it but same error occurred. How can I fix it?

**Comment by chrisb2** [comment]
Sorry for delay in replying, I was ill last week. 

So initially ran the following and it succeeded?
`sudo pip install pi-ina219`

You can verify if this worked with:
`pip list | grep ina219`

It should return:
`pi-ina219 (1.2.0)`

I presume 'ina219.py' is a test program can you post the contents?

Python 2 or 3 should work, you just have to use the matching pip command 'pip' for Python 2 and 'pip3' for Python 3.

regards,
Chris

**Comment by syjsxxjy** [comment]
![image](https://user-images.githubusercontent.com/7524140/57575758-f4ed9d80-748b-11e9-9b4b-a335e97012a8.png)
![image](https://user-images.githubusercontent.com/7524140/57575770-177fb680-748c-11e9-9b6c-cadf6e38bf53.png)
![image](https://user-images.githubusercontent.com/7524140/57575771-20708800-748c-11e9-9000-3a3981f88927.png)
Yes, I can install it by pip and it returns pi-ina219,but cannot import name....

**Comment by syjsxxjy** [comment]
> Sorry for delay in replying, I was ill last week.
> 
> So you initially ran the following and it succeeded?
> `sudo pip install pi-ina219`
> 
> You can verify if this worked with:
> `pip list | grep ina219`
> 
> It should return:
> `pi-ina219 (1.2.0)`
> 
> I presume 'ina219.py' is a test program can you post the contents?
> 
> Python 2 or 3 should work, you just have to use the matching pip command 'pip' for Python 2 and 'pip3' for Python 3.
> 
> regards,
> Chris

I just give up . I copied your code file to my project and import works properly.

**Comment by chrisb2** [comment]
OK, good to hear you got it working.

**Comment by remoengineer** [comment]
The interpreter picked up your ina219.py as the module instead of your test program.  Simply rename the test program to something like ina219_test.py and it should get well.
