### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by Gbassous** [chrisb2/pi_ina219#18]
I used your library in my dissertation, I'd like your confirmation on the citation:
C. Borrill, T. Timmons, T. van Staveren, T. Kluyver, and S. Bauer, “pi_ina219” 2019. [Online]. Available: https://github.com/chrisb2/pi_ina219. [Accessed: 24-Jul-2019].

**Comment by chrisb2** [comment]
Sorry for delay in replying, that is correct.

Chris
