### ISSUE TITLE
The library could not be imported in python >3.4

### ISSUE THREAD

**Issue by alcheagle** [chrisb2/pi_ina219#6]
I suggest adding 'Programming Language :: Python :: 3' inside ``setup.py`` classifiers instead of 'Programming Language :: Python :: 3.4'

**Comment by chrisb2** [comment]
I had a look around and found this
https://packaging.python.org/tutorials/distributing-packages/#classifiers
which would seem to suggest it should perhaps be:

'Programming Language :: Python :: 2',
'Programming Language :: Python :: 2.7',
'Programming Language :: Python :: 3',
'Programming Language :: Python :: 3.4',

regards,
Chris

**Comment by chrisb2** [comment]
I tested installing library on Raspbian Stretch:

`python -V`
gives 2.7.13
`sudo pip install pi-ina219`
succeeds.

`python3 -V`
gives 3.5.3
`sudo pip3 install pi-ina219`
succeeds.

Please can you provide more detail on the failure you observed.

thanks,
Chris

**Comment by alcheagle** [comment]
The problem occurred while I imported them inside python code. I tested to import it inside of a docker container because I suspect that the problem is my python environment that is broken in some way. Now the import is working. I think I need to do a cleanup of my system. 

Sorry to bother and thanks,
Andrea.
