### ISSUE TITLE
addressing i2c bus numbers > 1

### ISSUE THREAD

**Issue by eXodus1440** [chrisb2/pi_ina219#9]
Hi Chris,

I've been attempting to use your library with an Intel UpSquared and ran into an issue with the Intel's bus numbering system - their GPIO bus is 5 rather than the RPi default (assuming 1)

I made the following changes to ina219.py get it working on my project

`def __init__(self, shunt_ohms, max_expected_amps=None, busnum=None, address=__ADDRESS, log_level=logging.ERROR):`
`    self._i2c = I2C.get_i2c_device(address=address, busnum=busnum)`

Cheers,
Steve

**Comment by chrisb2** [comment]
That looks like a good change, can you submit a Pull Request? This should not affect RPi since if None is passed as busnum to get_i2c_device() this method tries to determine default of the board, see [I2C](https://github.com/adafruit/Adafruit_Python_GPIO/blob/c543d1df9c0a71bafb9f0a1f9dceecd79a920e74/Adafruit_GPIO/I2C.py#L64). 

thanks,
Chris

**Comment by eXodus1440** [comment]
Will do, will be later in the week tho

Cheers,
Steve

On 29 Apr 2018, at 05:12, Chris Borrill <notifications@github.com<mailto:notifications@github.com>> wrote:


That looks like a good change, can you submit a Pull Request? This should not affect RPi since if None is passed as busnum to get_i2c_device() this method tries to determine default of the board, see I2C<https://github.com/adafruit/Adafruit_Python_GPIO/blob/c543d1df9c0a71bafb9f0a1f9dceecd79a920e74/Adafruit_GPIO/I2C.py#L64>.

thanks,
Chris

**Comment by eXodus1440** [comment]
Hi Chris,

I'm trying to submit the PR but it's saying I don't have permissions, any ideas?

Just in case I was doing something silly, I also followed the below:
https://yangsu.github.io/pull-request-tutorial/

Regards,
Steve

**Comment by chrisb2** [comment]
Do you mean you cannot create the PR?

Chris

**Comment by chrisb2** [comment]
Assuming you forked my repo you would do "New pull request", add a comment
about your submission, then do " Create pull request"

**Comment by chrisb2** [comment]
Version 1.2.0 containing this improvement has been upload to pypi: [pi-ina219](https://pypi.org/project/pi-ina219/)
